### ISSUE TITLE
user can view a list of animations

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/ajax-project#2]
functionality: user can view the list of animations from Ghibli Studio. This is going to be the first page user will see. All the animation titles are clickable, which will lead to animation details. 

## ✅ Task List
- [x] build a basic HTML. Outline the page referencing the Figma model. 
- [x] decide how to organize the page.
- [x] pick a font to use for styling
- [x] pick a color scheme to use for the page
- [x] fetch the data from API address 
- [x] create a DOM tree with the following data. append to the correct position.
- [x] apply necessary styling for the HTML
- [x] fix all bugs
- [x] check if animations are displayed as intended.
