### ISSUE TITLE
User can view the details of animations

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/ajax-project#3]
functionality: Once the user clicks on the animation title from the main page, it will redirect the user to the corresponding animation page listing all the details related to the animation.

## ✅ Task List
- [x] add "a" tags to the images
- [x] add an event listener to the "a" tags to listen for the "click"
- [x] for the callback function, it will switch up the view and take the user to the "animation detail" page
- [x] create a DOM tree accordingly to the animation.
- [x] fetch data from new XMLHttpRequest
- [x] from the animation detail page, clicking the home button on the NavBar should take the user back to the main page.
- [x] add a favorite button on the bottom of the description section.
- [x] fix all bugs
